from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import AsyncIterator
from dataclasses import dataclass
from typing import Any


@dataclass
class VoiceEvent:
    type: str  # "transcript", "assistant_text", "audio", "tool_call", "interrupted", "turn_complete", "pipeline_event"
    payload: dict[str, Any]


class VoiceEngine(ABC):
    @abstractmethod
    async def start_session(self) -> None:
        """Initialize connection, authenticate, and prepare the session."""
        pass

    @abstractmethod
    async def send_audio(self, pcm: bytes) -> None:
        """Stream microphone audio PCM chunks into the engine."""
        pass

    @abstractmethod
    async def events(self) -> AsyncIterator[VoiceEvent]:
        """Stream high-level interaction events generated by the engine."""
        pass

    @abstractmethod
    async def cancel_response(self) -> None:
        """Interrupt and cancel the current model response (barge-in)."""
        pass

    @abstractmethod
    async def close(self) -> None:
        """Gracefully release session connections and local resources."""
        pass
